examples
example2

	| t2 |
	t2 := Bot new.
	t2 color: Color magenta.
			t2 extent: 200 @ 200.
			t2 extent: 100 @ 100.
			t2 penSize: 1.
			t2 penColor: Color brown.
			t2 go: 300.
			t2 turn: -92.
			t2 lookLikeTriangle.
			t2 go: 300.
			t2 extent: 50 @ 50.
			t2 turn: -92.
			t2 color: Color red.
			t2 go: 300.
			t2 turn: -92.
			t2 penSize: 3.
			t2 penColor: Color green.
			t2 lookLikeCircle.
			t2 go: 300.
			t2 turn: -92